modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

#issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="rpgpetmod" #mandatory

version="${file.jarVersion}" # 1.15.2 1.0.0

displayName="RPG Pet Mod"

# updateJSONURL="http://myurl.me/" #optional

# displayURL="http://example.com/" #optional

logoFile="rpgpetmod.png" #optional # in the root of the mod JAR

credits="This is credits"

authors="This is authors"

description='''
    This
        is description!
'''

[[dependencies.rpgpetmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory

    # BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # BOTH, CLIENT or SERVER
    side="BOTH"

[[dependencies.rpgpetmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
